#!/usr/bin/env python
"""
Mickey's own serial terminal. Based on miniterm.py.

Additional Features:
    * readline support with command completion and history
    * support for gsm0710muxd and fso-abyss
    * log to file

(C) 2002-2006 Chris Liechti <cliecht@gmx.net>
(C) 2008-2009 Michael 'Mickey' Lauer <mlauer@vanille-media.de>

GPLv2 or later
"""

__version__ = "2.9.1"

import sys, os, serial, threading, termios

def completer( text, state ):
    """Return a possible readline completion"""
    if state == 0:
        line =""
        #line = readline.get_line_buffer()
        if " " in line:
            allmatches = [ "(No Matches Available for commands.)" ]
        else:
            if not hasattr( completer, "commands" ):
                allmatches = [ "(No matches available yet. Did AT+CLAC yet?)" ]
            else:
                allmatches = completer.commands

        completer.matches = [ x for x in allmatches if x[:len(text)] == text ]
    if len( completer.matches ) > state:
        return completer.matches[state]
    else:
        return None

commands = """
AT+CACM
AT+CAMM
AT+CAOC
AT+CBC
AT+CBST
AT+CCFC
AT+CCUG
AT+CCWA
AT+CCWE
AT+CEER
AT+CFUN
AT+CGACT
AT+CGANS
AT+CGATT
AT+CGAUTO
AT+CGCLASS
AT+CGDATA
AT+CGDCONT
AT+CGEREP
AT+CGMI
AT+CGMM
AT+CGMR
AT+CGPADDR
AT+CGQMIN
AT+CGQREQ
AT+CGREG
AT+CGSMS
AT+CGSN
AT+CHLD
AT+CHUP
AT+CIMI
AT+CLAC
AT+CLAE
AT+CLAN
AT+CLCC
AT+CLCK
AT+CLIP
AT+CDIP
AT+CLIR
AT+CLVL
AT+CMEE
AT+CMGC
AT+CMGD
AT+CMGF
AT+CMGL
AT+CMGR
AT+CMGS
AT+CMGW
AT+CMOD
AT+CMSS
AT+CMMS
AT+CMUT
AT+CMUX
AT+CNMA
AT+CNMI
AT+CNUM
AT+COLP
AT+COPN
AT+COPS
AT+CPAS
AT+CPBF
AT+CPBR
AT+CPBS
AT+CPBW
AT+CPIN
AT+CPMS
AT+CPOL
AT+CPUC
AT+CPWD
AT+CR
AT+CRC
AT+CREG
AT+CRES
AT+CRLP
AT+CRSL
AT+CRSM
AT+CSAS
AT+CSCA
AT+CSCB
AT+CSCS
AT+CSDH
AT+CSIM
AT+CSMP
AT+CSMS
AT+CSNS
AT+CSQ
AT%CSQ
AT+CSSN
AT+CSTA
AT+CSVM
AT+CTFR
AT+CUSD
AT+DR
AT+FAP
AT+FBO
AT+FBS
AT+FBU
AT+FCC
AT+FCLASS
AT+FCQ
AT+FCR
AT+FCS
AT+FCT
AT+FDR
AT+FDT
AT+FEA
AT+FFC
AT+FHS
AT+FIE
AT+FIP
AT+FIS
AT+FIT
AT+FKS
AT+FLI
AT+FLO
AT+FLP
AT+FMI
AT+FMM
AT+FMR
AT+FMS
AT+FND
AT+FNR
AT+FNS
AT+FPA
AT+FPI
AT+FPS
AT+FPW
AT+FRQ
AT+FSA
AT+FSP
AT+GCAP
AT+GCI
AT+GMI
AT+GMM
AT+GMR
AT+GSN
AT+ICF
AT+IFC
AT+ILRR
AT+IPR
AT+VTS
AT+WS46
AT%ALS
AT%ATR
AT%BAND
AT%CACM
AT%CAOC
AT%CCBS
AT%STDR
AT%CGAATT
AT%CGMM
AT%CGREG
AT%CNAP
AT%CPI
AT%COLR
AT%CPRIM
AT%CTV
AT%CUNS
AT%NRG
AT%SATC
AT%SATE
AT%SATR
AT%SATT
AT%SNCNT
AT%VER
AT%CGCLASS
AT%CGPCO
AT%CGPPP
AT%EM
AT%EMET
AT%EMETS
AT%CBHZ
AT%CPHS
AT%CPNUMS
AT%CPALS
AT%CPVWI
AT%CPOPN
AT%CPCFU
AT%CPINF
AT%CPMB
AT%CPRI
AT%DATA
AT%DINF
AT%CLCC
AT%DBGINFO
AT%VTS
AT%CHPL
AT%CREG
AT+CTZR
AT+CTZU
AT%CTZV
AT%CNIV
AT%PVRF
AT%CWUP
AT%DAR
AT+CIND
AT+CMER
AT%CSCN
AT%RDL
AT%RDLB
AT%CSTAT
AT%CPRSM
AT%CHLD
AT%SIMIND
AT%SECP
AT%SECS
AT%CSSN
AT+CCLK
AT%CSSD
AT%COPS
AT%CPMBW
AT%CUST
AT%SATCC
AT%COPN
AT%CGEREP
AT%CUSCFG
AT%CUSDR
AT%CPBS
AT%PBCF
AT%SIMEF
AT%EFRSLT
AT%CMGMDU
AT%CMGL
AT%CMGR
AT@ST
AT@AUL
AT@POFF
AT@RST
AT@SC
AT@BAND
ATA
ATB
AT&C
ATD
AT&D
ATE
ATF
AT&F
ATH
ATI
AT&K
ATL
ATM
ATO
ATP
ATQ
ATS
ATT
ATV
ATW
AT&W
ATX
ATZ
""".strip()
completer.commands = commands.split() + commands.lower().split()

class Terminal( object ):
    def __init__( self, port, baudrate, rtscts, xonxoff, lineending, inputmode=True ):
        self.inputmode = inputmode
        self.r = None
        self.convert = lineending
        self.EXITCHARACTER = '\x04' # ctrl+D
        self.fd = None
        self.serial = serial.Serial( port, baudrate, rtscts=rtscts, xonxoff=xonxoff )

    def setQuietMode( self, quiet ):
        self.quiet = quiet

    def setLogging( self, logging ):
        self.logging = logging
        if self.logging is not None:
            self.ilog = open( "%s/mickeyterm.%d.input" % ( logging, os.getpid() ), "w" )
            self.olog = open( "%s/mickeyterm.%d.output" % ( logging, os.getpid() ), "w" )
            self.alog = open( "%s/mickeyterm.%d.all" % ( logging, os.getpid() ), "w" )

    def run( self ):
        self.prepare()
        self.serial.open()
        assert self.serial.isOpen(), "can't open serial port"
        self.banner( True )
        self.r = threading.Thread( target = self.reader )
        self.r.setDaemon( True )
        self.r.start()
        # optional
        self.serial.write( "AT+CMEE=2;+CRC=1\r\n" )
        self.writer()
        self.banner( False )
        self.serial.close()
        self.restore()

    def banner( self, startup ):
        if self.quiet:
            return
        if startup:
            print "<----------- Mickey's Term V%s @ %s ----------->" % ( __version__, self.serial.port )
        else:
            print "Good Bye."

    def prepare( self ):
        if self.inputmode:
            import readline
            readline.set_completer( completer )
            readline.set_completer_delims( " " )
            readline.parse_and_bind("tab: complete")
            self.historyfilename = os.path.expanduser( "~/.mickeyterm_history" )
            try:
                readline.read_history_file( self.historyfilename )
                print "read history from", self.historyfilename
            except IOError:
                readline.clear_history()

        else:
            self.fd = sys.stdin.fileno()
            self.old = termios.tcgetattr( self.fd )
            new = termios.tcgetattr( self.fd )
            new[3] = new[3] & ~termios.ICANON & ~termios.ECHO & ~termios.ISIG
            new[6][termios.VMIN] = 1
            new[6][termios.VTIME] = 0
            termios.tcsetattr( self.fd, termios.TCSANOW, new )

    def restore( self ):
        if self.inputmode:
            import readline
            try:
                readline.write_history_file( self.historyfilename )
            except IOError, e:
                print "Could not save history.", repr(e)
        else:
            termios.tcsetattr( self.fd, termios.TCSAFLUSH, self.old )

    def writer( self ):
        if self.inputmode:
            #
            # new style
            #
            while True:
                try:
                    cmdline = raw_input( "" )
                except KeyboardInterrupt:
                    print "CTRL-C"
                    continue
                except EOFError:
                    print "CTRL-D"
                    break
                else:
                    if self.convert == "CRLF":
                        cmdline += "\r\n"
                    elif self.convert == "CR":
                        cmdline += "\r"
                    elif self.convert == "LF":
                        cmdline += "\n"
                    self.serial.write( cmdline )
                    if self.logging:
                        self.ilog.write( cmdline )
                        self.alog.write( cmdline )
        else:
            #
            # old style
            #
            while True:
                c = os.read( self.fd, 1 )
                if c == self.EXITCHARACTER:
                    break
                elif c == '\n':
                    if self.convert == "CRLF":
                        self.serial.write('\r\n')
                    elif self.convert == "CR":
                        self.serial.write('\r')
                    elif self.convert == "LF":
                        self.serial.write('\n')
                else:
                    self.serial.write(c)
                    if self.logging:
                        self.ilog.write( c )
                        self.alog.write( c )

    def reader( self ):
        while True:
            data = self.serial.read()
            sys.stdout.write(data)
            sys.stdout.flush()
            if self.logging:
                self.olog.write( data )
                self.alog.write( data )


if __name__ == "__main__":
    import optparse

    parser = optparse.OptionParser(usage="""\
%prog [options] [port [baudrate]]

Mickey's Terminal Program.""")

    parser.add_option("-p", "--port", dest="port",
        help="the port, device path, a portnumber, device name (deprecated option), or MUX (default)",
        default="MUX")

    parser.add_option("-b", "--baud", dest="baudrate", action="store", type='int',
        help="set baudrate, default 115200", default=115200)

    parser.add_option("", "--parity", dest="parity", action="store",
        help="set parity, one of [N, E, O], default=N", default='N')

    if False:
        parser.add_option("-e", "--echo", dest="echo", action="store_true",
            help="enable local echo (default off)", default=False)

    parser.add_option("", "--rtscts", dest="rtscts", action="store_true",
        help="enable RTS/CTS flow control (default off)", default=False)

    parser.add_option("", "--xonxoff", dest="xonxoff", action="store_true",
        help="enable software flow control (default off)", default=False)

    parser.add_option("", "--cr", dest="cr", action="store_true",
        help="do not send CR+LF, send CR only", default=False)

    parser.add_option("", "--lf", dest="lf", action="store_true",
        help="do not send CR+LF, send LF only", default=False)

    if False:
        parser.add_option("-D", "--debug", dest="repr_mode", action="count",
            help="""debug received data (escape non-printable chars)
    --debug can be given multiple times:
    0: just print what is received
    1: escape non-printable characters, do newlines as ususal
    2: escape non-printable characters, newlines too
    3: hex dump everything""", default=0)

    parser.add_option("", "--rts", dest="rts_state", action="store", type='int',
        help="set initial RTS line state (possible values: 0, 1)", default=None)

    parser.add_option("", "--dtr", dest="dtr_state", action="store", type='int',
        help="set initial DTR line state (possible values: 0, 1)", default=None)

    # behaviour

    parser.add_option("-c", "--char-by-char", dest="charbychar", action="store_true",
        help="use character-by-character (traditional mode) instead of line-by-line (default)",
        default=False)

    parser.add_option("-l", "--logdir", dest="log",
        help="enable logging to files, specifies directory" )

    parser.add_option("-q", "--quiet", dest="quiet", action="store_true",
        help="suppress non error messages", default=False)

    options, args = parser.parse_args()

    if options.cr and options.lf:
        parser.error("only one of --cr or --lf can be specified")
    else:
        if options.cr:
            lineending = "CR"
        elif options.lf:
            lineending = "LF"
        else:
            lineending = "CRLF"

    port = options.port
    baudrate = options.baudrate
    if args:
        if options.port is not None:
            parser.error("no arguments are allowed, options only when --port is given")
        port = args.pop(0)
        if args:
            try:
                baudrate = int(args[0])
            except ValueError:
                parser.error("baudrate must be a number, not %r" % args[0])
            args.pop(0)
        if args:
            parser.error("too many arguments")
    else:
        if port is "MUX":
            # try to get portname from old-style MUXer
            import dbus
            bus = dbus.SystemBus()
            oMuxer = bus.get_object( "org.pyneo.muxer", "/org/pyneo/Muxer" )
            iMuxer = dbus.Interface( oMuxer, "org.freesmartphone.GSM.MUX" )
            port = iMuxer.AllocChannel( "mickeyterm.%d" % os.getpid() )
            assert port, "could not get path from gsm0710muxd. need to supply explicit portname"

        elif port.startswith( "fso" ):
            fso, channel = port.split( ':', 1 )
            number = int( channel )
            import dbus
            bus = dbus.SystemBus()
            oMuxer = bus.get_object( "org.freesmartphone.omuxerd", "/org/freesmartphone/GSM/Muxer" )
            iMuxer = dbus.Interface( oMuxer, "org.freesmartphone.GSM.MUX" )
            port, channel = iMuxer.AllocChannel( "mickeyterm.%d" % os.getpid(), number )
            assert port, "could not get path from fso-abyss. need to supply explicit portname"

    if options.log is not None:
        if not os.path.isdir( options.log ):
            parser.error("%s not a directory")

    inputmode = not options.charbychar

    t = Terminal( str(port), baudrate, options.rtscts, options.xonxoff, lineending, inputmode )
    t.setQuietMode( options.quiet )
    t.setLogging( options.log )
    t.run()
